### ISSUE TITLE
Browser opens tmp file as source, not html

### ISSUE THREAD

**Issue by petterssonjonas** [doczi-dominik/colorlist#1]
$ ./colorlist.py ~/.config/rofi/themes/colorschemes/gruvbox.rasi as example, and brave set as $BROWSER opens file:///tmp/colorlist_gruvbox.rasi_0naxfwl9 and shows the html code.
Adding .html to the end fixes it.

Do you think you could add more color code options? For example alacritty config uses hex code for colors, i think..? I'd like to be able to translate color codes and make sure i have them uniform across configs and projects.

**Comment by doczi-dominik** [comment]
You should checkout the Usage section of the README, specifically the section called Formats, where you can specify custom color templates.


As for the `.html` issue, thank you for the heads up, I'll fix it as soon as I get near my laptop.
